services:
  postgres:
    image: postgres
    volumes:
      - db:/DB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  db: