services:
  mongo:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo:/etc/mongo:rw
    networks:
      - backend
volumes:
  mongo:

networks:
  backend:
    driver: bridge
