spring:
  config:
      import:
        file:.env[.properties]
  application:
    name: todo-cause-why-not
  data: 
    mongodb:
      host: localhost
      port: ${MONGO_PORT}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DB}
      
