spring:
  application:
    name: todo-cause-why-not
  data:
    mongodb:
      host: ${MONGO_HOST}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}